pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo "Suraj's file"
            }
        }
        stage('Test') {
            steps {
                echo "Suraj's file"
            }
            post {
                always {
                    echo "Suraj's file"
                }
            }
        }
        stage('Deliver') { 
            steps {
                echo "Suraj's file"
            }
        }
        stage('Complete') { 
            steps {
                echo "Suraj's file"
            }
        }
    }
}
